### ISSUE TITLE
Fix compatibility with sonar 5.6

### ISSUE THREAD

**Issue by FROSADO** [SonarQubeCommunity/sonar-cobertura#8]
http://docs.sonarqube.org/display/PLUG/Plugin+Version+Matrix indicate that sonar 5.6 have broken the compatibility

**Comment by m-g-sonar** [comment]
Version 1.7, currently under test is solving the issue. Please follow this thread: https://groups.google.com/d/topic/sonarqube/AGGQJLa1KZA/discussion
